kind: pipeline
name: default

workspace:
  path: /test-package-manager-cache

trigger:
  branch:
    - master

steps:
  - name: echo-npm
    image: chiskat/baseline-node20:2026.4.26
    commands:
      - npm i
      - node npm.js

  - name: echo-yarn
    image: chiskat/baseline-node20:2026.4.26
    commands:
      - yarn
      - node yarn.js

  - name: echo-pnpm
    image: chiskat/baseline-node20:2026.4.26
    commands:
      - pnpm i
      - node pnpm.js
