name: container 模式 npm

on:
  push:
    branches:
      - master

jobs:
  npm:
    runs-on: ubuntu-latest
    container:
      image: node:22

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 配置 npm 缓存
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: node-cache-${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: node-cache-${{ runner.os }}-npm-

      - name: 安装依赖并执行测试
        run: |
          npm i
          node npm.js
