name: container 模式 

on:
  push:
    branches:
      - master

jobs:
  yarn:
    runs-on: ubuntu-latest
    container:
      image: node:22

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 安装依赖并执行测试
        run: |
          yarn
          node yarn.js
