name: setup-node 模式 yarn

on:
  push:
    branches:
      - master

jobs:
  yarn:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 安装 node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: 安装依赖并执行测试
        run: |
          yarn
          node yarn.js
