name: setup-node 模式 npm

on:
  push:
    branches:
      - master

jobs:
  npm:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 安装 node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: 安装依赖并执行测试
        run: |
          npm i
          node npm.js
